---
title: State of Equity Agenda
timezone: America/New_York
collections:
  outcome:
    title: Outcome
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: outcome
  values:
    layout: outcome
    strategies:
    - title: ''
      text: ''
      policies:
      - title: ''
        text: ''
      best_practice:
        text: ''
      viz_id: ''
author: Eric Youngberg
email: eyoungberg@mapc.org
encoding: utf-8
host: 0.0.0.0
port: 4000
livereload: true
reload_port: 5678
exclude_from_watch:
- nasa
- node_modules
- package.json
- package-lock.json
exclude:
- package.json
- package-lock.json
- node_modules
- nasa
- Gulpfile.js
- docker-compose.yml
- Dockerfile
- README.md
